/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/connexion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Authentification : renvoie les jetons et le profil (EF-01). */
        post: operations["auth_connexion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mot-de-passe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description EF-05. */
        post: operations["auth_mot_de_passe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profil/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Profil de l'utilisateur connecté. */
        get: operations["auth_profil_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Profil de l'utilisateur connecté. */
        patch: operations["auth_profil_partial_update"];
        trace?: never;
    };
    "/api/auth/rafraichir/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_rafraichir_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verifier/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_verifier_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enregistre une dose. Le moteur valide l'âge minimal et l'intervalle entre doses ; les échéances suivantes sont re-planifiées (RG-04). Rejouer la même clé d'idempotence ne crée pas de doublon (EF-54). */
        post: operations["doses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/echeances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Consultation des échéances vaccinales.
         *
         *     Les échéances ne se créent ni ne se modifient directement : elles sont
         *     produites par le moteur de calendrier. Seules l'administration d'une dose
         *     et l'annulation les font évoluer.
         */
        get: operations["echeances_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/echeances/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Consultation des échéances vaccinales.
         *
         *     Les échéances ne se créent ni ne se modifient directement : elles sont
         *     produites par le moteur de calendrier. Seules l'administration d'une dose
         *     et l'annulation les font évoluer.
         */
        get: operations["echeances_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/echeances/{id}/annuler/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Annule une échéance (EF-27). Aucun rappel ne sera plus émis (RG-08). */
        post: operations["echeances_annuler_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/echeances/file-du-jour/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File du jour (EF-42) : échéances en retard, plus celles dues dans les prochains jours. Une échéance dont la date cible est dépassée mais qui reste dans sa fenêtre de rattrapage n'encombre pas la file tant qu'elle n'est pas proche de sa limite. */
        get: operations["echeances_file_du_jour_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enfants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        get: operations["enfants_list"];
        put?: never;
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        post: operations["enfants_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enfants/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        get: operations["enfants_retrieve"];
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        put: operations["enfants_update"];
        post?: never;
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        delete: operations["enfants_destroy"];
        options?: never;
        head?: never;
        /** @description Enfants bénéficiaires (EF-12, EF-14). */
        patch: operations["enfants_partial_update"];
        trace?: never;
    };
    "/api/enfants/{id}/calendrier/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Calendrier vaccinal complet de l'enfant (EF-20, EF-22, EF-24). */
        get: operations["enfants_calendrier_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grossesses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Épisodes de grossesse (EF-11). */
        get: operations["grossesses_list"];
        put?: never;
        /** @description Épisodes de grossesse (EF-11). */
        post: operations["grossesses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grossesses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Épisodes de grossesse (EF-11). */
        get: operations["grossesses_retrieve"];
        /** @description Épisodes de grossesse (EF-11). */
        put: operations["grossesses_update"];
        post?: never;
        /** @description Épisodes de grossesse (EF-11). */
        delete: operations["grossesses_destroy"];
        options?: never;
        head?: never;
        /** @description Épisodes de grossesse (EF-11). */
        patch: operations["grossesses_partial_update"];
        trace?: never;
    };
    "/api/grossesses/{id}/calendrier/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Calendrier antitétanique de la grossesse (EF-21). */
        get: operations["grossesses_calendrier_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meres/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mères et futures mères (EF-10, EF-14). */
        get: operations["meres_list"];
        put?: never;
        /** @description Mères et futures mères (EF-10, EF-14). */
        post: operations["meres_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meres/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mères et futures mères (EF-10, EF-14). */
        get: operations["meres_retrieve"];
        /** @description Mères et futures mères (EF-10, EF-14). */
        put: operations["meres_update"];
        post?: never;
        /** @description Mères et futures mères (EF-10, EF-14). */
        delete: operations["meres_destroy"];
        options?: never;
        head?: never;
        /** @description Mères et futures mères (EF-10, EF-14). */
        patch: operations["meres_partial_update"];
        trace?: never;
    };
    "/api/meres/{id}/consentement/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enregistre un consentement aux rappels (ENF-21). */
        post: operations["meres_consentement_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meres/{id}/revoquer-consentement/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Révoque le consentement actif. Sans effet s'il n'y en a pas. */
        post: operations["meres_revoquer_consentement_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Référentiel des postes, en lecture seule hors administration. */
        get: operations["postes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Référentiel des postes, en lecture seule hors administration. */
        get: operations["postes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnnulationRequest: {
            motif: components["schemas"]["MotifEnum"];
            /** @default  */
            commentaire: string;
        };
        /**
         * @description * `whatsapp` - WhatsApp
         *     * `sms` - SMS
         *     * `application` - Application uniquement
         * @enum {string}
         */
        CanalEnum: "whatsapp" | "sms" | "application";
        ChangementMotDePasseRequest: {
            ancien_mot_de_passe: string;
            nouveau_mot_de_passe: string;
        };
        /**
         * @description Ajoute le profil à la réponse de connexion.
         *
         *     Sans cela, le client devrait enchaîner un second appel pour savoir qui il
         *     est et à quel poste il est rattaché — deux allers-retours là où un seul
         *     suffit, sur des connexions souvent mauvaises.
         */
        ConnexionRequest: {
            username: string;
            password: string;
        };
        Consentement: {
            readonly id: number;
            /** Canal accepté */
            canal?: components["schemas"]["CanalEnum"];
            /**
             * Accordé le
             * Format: date-time
             */
            readonly accorde_le: string;
            /**
             * Révoqué le
             * Format: date-time
             */
            readonly revoque_le: string | null;
            readonly recueilli_par: string;
            readonly actif: boolean;
        };
        ConsentementRequest: {
            /** Canal accepté */
            canal?: components["schemas"]["CanalEnum"];
        };
        CreationConsentementRequest: {
            canal: components["schemas"]["CanalEnum"];
        };
        /** @description Entrée de l'enregistrement d'un acte vaccinal (EF-30). */
        CreationDoseRequest: {
            /** Format: uuid */
            echeance_id: string;
            /** Format: date */
            date_administration: string;
            /** @default  */
            numero_lot: string;
            /**
             * Format: uuid
             * @description Générée par le client. Permet de rejouer sans doublon (EF-54).
             */
            cle_idempotence?: string | null;
            /** @default  */
            evenement_indesirable: string;
        };
        Dose: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Date d'administration
             * Format: date
             */
            readonly date_administration: string;
            /** Numéro de lot */
            readonly numero_lot: string;
            readonly agent: string;
            /** Événement indésirable */
            readonly evenement_indesirable: string;
            /** Format: date-time */
            readonly cree_le: string;
        };
        Echeance: {
            /** Format: uuid */
            readonly id: string;
            readonly vaccin_code: string;
            readonly vaccin_libelle: string;
            /** Rang de la dose */
            readonly rang: number;
            /**
             * Date d'ouverture
             * Format: date
             */
            readonly date_ouverture: string;
            /** Format: date */
            readonly date_cible: string;
            /** Format: date */
            readonly date_limite: string | null;
            readonly statut: components["schemas"]["Statut184Enum"];
            /** Motif d'annulation */
            readonly motif_annulation: components["schemas"]["MotifAnnulationEnum"];
            readonly retard_jours: number;
            readonly dose: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description Vue enrichie pour la file du jour de l'agent (EF-42).
         *
         *     Le nom du bénéficiaire et son téléphone sont inclus pour éviter à
         *     l'interface d'enchaîner une requête par ligne.
         */
        EcheanceFile: {
            /** Format: uuid */
            readonly id: string;
            readonly vaccin_code: string;
            readonly vaccin_libelle: string;
            /** Rang de la dose */
            readonly rang: number;
            /**
             * Date d'ouverture
             * Format: date
             */
            readonly date_ouverture: string;
            /** Format: date */
            readonly date_cible: string;
            /** Format: date */
            readonly date_limite: string | null;
            readonly statut: components["schemas"]["Statut184Enum"];
            /** Motif d'annulation */
            readonly motif_annulation: components["schemas"]["MotifAnnulationEnum"];
            readonly retard_jours: number;
            readonly dose: {
                [key: string]: unknown;
            } | null;
            readonly beneficiaire_nom: string;
            readonly beneficiaire_id: string;
            readonly beneficiaire_type: string;
            readonly telephone: string;
        };
        Enfant: {
            /** Format: uuid */
            readonly id: string;
            readonly mere: components["schemas"]["MereListe"];
            /** Prénom */
            prenom?: string;
            nom?: string;
            readonly nom_complet: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance: string;
            sexe: components["schemas"]["SexeEnum"];
            /**
             * Semaines de gestation à la naissance
             * @description Moins de 37 semaines : prématuré.
             */
            semaines_gestation?: number | null;
            /** Poids de naissance (g) */
            poids_naissance_grammes?: number | null;
            readonly est_premature: boolean;
            readonly age_jours: number;
            /** Format: date-time */
            readonly cree_le: string;
        };
        EnfantListe: {
            /** Format: uuid */
            readonly id: string;
            readonly nom_complet: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance: string;
            sexe: components["schemas"]["SexeEnum"];
            readonly mere_nom: string;
        };
        EnfantRequest: {
            /** Format: uuid */
            mere_id: string;
            /** Prénom */
            prenom?: string;
            nom?: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance: string;
            sexe: components["schemas"]["SexeEnum"];
            /**
             * Semaines de gestation à la naissance
             * @description Moins de 37 semaines : prématuré.
             */
            semaines_gestation?: number | null;
            /** Poids de naissance (g) */
            poids_naissance_grammes?: number | null;
        };
        Grossesse: {
            /** Format: uuid */
            readonly id: string;
            readonly mere: components["schemas"]["MereListe"];
            /** Rang de la grossesse */
            rang?: number;
            /**
             * Date du premier contact prénatal
             * Format: date
             */
            date_reference: string;
            /**
             * Terme estimé
             * Format: date
             */
            terme_estime?: string | null;
            statut?: components["schemas"]["GrossesseStatutEnum"];
            /** Format: date-time */
            readonly cree_le: string;
        };
        GrossesseRequest: {
            /** Format: uuid */
            mere_id: string;
            /** Rang de la grossesse */
            rang?: number;
            /**
             * Date du premier contact prénatal
             * Format: date
             */
            date_reference: string;
            /**
             * Terme estimé
             * Format: date
             */
            terme_estime?: string | null;
            statut?: components["schemas"]["GrossesseStatutEnum"];
        };
        /**
         * @description * `en_cours` - En cours
         *     * `terminee` - Terminée
         *     * `interrompue` - Interrompue
         * @enum {string}
         */
        GrossesseStatutEnum: "en_cours" | "terminee" | "interrompue";
        /**
         * @description * `fr` - Français
         *     * `wo` - Wolof
         * @enum {string}
         */
        LangueEnum: "fr" | "wo";
        /** @description Vue complète d'une mère, pour sa fiche. */
        Mere: {
            /** Format: uuid */
            readonly id: string;
            /** Prénom */
            prenom: string;
            nom: string;
            readonly nom_complet: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance?: string | null;
            /** Téléphone */
            telephone?: string;
            /** Langue préférée */
            langue?: components["schemas"]["LangueEnum"];
            /** Village ou quartier */
            village?: string;
            readonly accepte_les_rappels: boolean;
            readonly consentements: components["schemas"]["Consentement"][];
            readonly nombre_enfants: number;
            /** Format: date-time */
            readonly cree_le: string;
        };
        /**
         * @description Vue allégée pour les listes et la recherche.
         *
         *     Charger les consentements de trente mères dans une liste serait du gaspillage
         *     de bande passante, sur des connexions qui n'en ont pas à revendre.
         */
        MereListe: {
            /** Format: uuid */
            readonly id: string;
            /** Prénom */
            prenom: string;
            nom: string;
            readonly nom_complet: string;
            /** Téléphone */
            telephone?: string;
            /** Village ou quartier */
            village?: string;
        };
        /**
         * @description Vue allégée pour les listes et la recherche.
         *
         *     Charger les consentements de trente mères dans une liste serait du gaspillage
         *     de bande passante, sur des connexions qui n'en ont pas à revendre.
         */
        MereListeRequest: {
            /** Prénom */
            prenom: string;
            nom: string;
            /** Téléphone */
            telephone?: string;
            /** Village ou quartier */
            village?: string;
        };
        /** @description Vue complète d'une mère, pour sa fiche. */
        MereRequest: {
            /** Prénom */
            prenom: string;
            nom: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance?: string | null;
            /** Téléphone */
            telephone?: string;
            /** Langue préférée */
            langue?: components["schemas"]["LangueEnum"];
            /** Village ou quartier */
            village?: string;
        };
        /**
         * @description * `contre_indication` - Contre-indication médicale
         *     * `deces` - Décès
         *     * `demenagement` - Déménagement
         *     * `refus` - Refus des parents
         *     * `autre` - Autre
         * @enum {string}
         */
        MotifAnnulationEnum: "contre_indication" | "deces" | "demenagement" | "refus" | "autre";
        /**
         * @description * `contre_indication` - Contre-indication médicale
         *     * `deces` - Décès
         *     * `demenagement` - Déménagement
         *     * `refus` - Refus des parents
         *     * `autre` - Autre
         * @enum {string}
         */
        MotifEnum: "contre_indication" | "deces" | "demenagement" | "refus" | "autre";
        PaginatedEcheanceFileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["EcheanceFile"][];
        };
        PaginatedEcheanceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Echeance"][];
        };
        PaginatedEnfantListeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["EnfantListe"][];
        };
        PaginatedGrossesseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Grossesse"][];
        };
        PaginatedMereListeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MereListe"][];
        };
        PaginatedPosteSanteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PosteSante"][];
        };
        PatchedEnfantRequest: {
            /** Format: uuid */
            mere_id?: string;
            /** Prénom */
            prenom?: string;
            nom?: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance?: string;
            sexe?: components["schemas"]["SexeEnum"];
            /**
             * Semaines de gestation à la naissance
             * @description Moins de 37 semaines : prématuré.
             */
            semaines_gestation?: number | null;
            /** Poids de naissance (g) */
            poids_naissance_grammes?: number | null;
        };
        PatchedGrossesseRequest: {
            /** Format: uuid */
            mere_id?: string;
            /** Rang de la grossesse */
            rang?: number;
            /**
             * Date du premier contact prénatal
             * Format: date
             */
            date_reference?: string;
            /**
             * Terme estimé
             * Format: date
             */
            terme_estime?: string | null;
            statut?: components["schemas"]["GrossesseStatutEnum"];
        };
        /** @description Vue complète d'une mère, pour sa fiche. */
        PatchedMereRequest: {
            /** Prénom */
            prenom?: string;
            nom?: string;
            /**
             * Date de naissance
             * Format: date
             */
            date_naissance?: string | null;
            /** Téléphone */
            telephone?: string;
            /** Langue préférée */
            langue?: components["schemas"]["LangueEnum"];
            /** Village ou quartier */
            village?: string;
        };
        /** @description Profil de l'utilisateur connecté. */
        PatchedUtilisateurRequest: {
            /** Prénom */
            first_name?: string;
            /** Nom */
            last_name?: string;
            /** Adresse électronique */
            email?: string;
            /** Téléphone */
            telephone?: string;
            langue?: components["schemas"]["LangueEnum"];
        };
        PosteSante: {
            /** Format: uuid */
            readonly id: string;
            readonly nom: string;
            readonly district: string;
            /** Région */
            readonly region: string;
            readonly actif: boolean;
        };
        /**
         * @description * `agent` - Agent de santé
         *     * `superviseur` - Superviseur de district
         *     * `admin` - Administrateur
         * @enum {string}
         */
        RoleEnum: "agent" | "superviseur" | "admin";
        /**
         * @description * `F` - Féminin
         *     * `M` - Masculin
         * @enum {string}
         */
        SexeEnum: "F" | "M";
        /**
         * @description * `a_venir` - À venir
         *     * `due` - Due
         *     * `en_retard` - En retard
         *     * `administree` - Administrée
         *     * `annulee` - Annulée
         * @enum {string}
         */
        Statut184Enum: "a_venir" | "due" | "en_retard" | "administree" | "annulee";
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /** @description Profil de l'utilisateur connecté. */
        Utilisateur: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Nom d’utilisateur
             * @description Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères « @ », « . », « + », « - » et « _ ».
             */
            readonly username: string;
            /** Prénom */
            first_name?: string;
            /** Nom */
            last_name?: string;
            readonly nom_complet: string;
            /** Adresse électronique */
            email?: string;
            /** Rôle */
            readonly role: components["schemas"]["RoleEnum"];
            readonly poste: components["schemas"]["PosteSante"];
            /** Téléphone */
            telephone?: string;
            langue?: components["schemas"]["LangueEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_connexion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnexionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConnexionRequest"];
                "multipart/form-data": components["schemas"]["ConnexionRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mot_de_passe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementMotDePasseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangementMotDePasseRequest"];
                "multipart/form-data": components["schemas"]["ChangementMotDePasseRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profil_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilisateur"];
                };
            };
        };
    };
    auth_profil_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUtilisateurRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUtilisateurRequest"];
                "multipart/form-data": components["schemas"]["PatchedUtilisateurRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilisateur"];
                };
            };
        };
    };
    auth_rafraichir_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_verifier_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    doses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationDoseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreationDoseRequest"];
                "multipart/form-data": components["schemas"]["CreationDoseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dose"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    echeances_list: {
        parameters: {
            query?: {
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEcheanceList"];
                };
            };
        };
    };
    echeances_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Echeance"];
                };
            };
        };
    };
    echeances_annuler_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnulationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AnnulationRequest"];
                "multipart/form-data": components["schemas"]["AnnulationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Echeance"];
                };
            };
        };
    };
    echeances_file_du_jour_list: {
        parameters: {
            query?: {
                /** @description Jour ciblé (AAAA-MM-JJ). Par défaut : aujourd'hui. */
                date?: string;
                /** @description Nombre de jours à venir inclus. Défaut : 7. */
                horizon?: number;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEcheanceFileList"];
                };
            };
        };
    };
    enfants_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Un terme de recherche. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEnfantListeList"];
                };
            };
        };
    };
    enfants_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnfantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EnfantRequest"];
                "multipart/form-data": components["schemas"]["EnfantRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enfant"];
                };
            };
        };
    };
    enfants_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enfant"];
                };
            };
        };
    };
    enfants_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnfantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EnfantRequest"];
                "multipart/form-data": components["schemas"]["EnfantRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enfant"];
                };
            };
        };
    };
    enfants_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enfants_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEnfantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEnfantRequest"];
                "multipart/form-data": components["schemas"]["PatchedEnfantRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enfant"];
                };
            };
        };
    };
    enfants_calendrier_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grossesses_list: {
        parameters: {
            query?: {
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGrossesseList"];
                };
            };
        };
    };
    grossesses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrossesseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GrossesseRequest"];
                "multipart/form-data": components["schemas"]["GrossesseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grossesse"];
                };
            };
        };
    };
    grossesses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grossesse"];
                };
            };
        };
    };
    grossesses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrossesseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GrossesseRequest"];
                "multipart/form-data": components["schemas"]["GrossesseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grossesse"];
                };
            };
        };
    };
    grossesses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grossesses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGrossesseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGrossesseRequest"];
                "multipart/form-data": components["schemas"]["PatchedGrossesseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grossesse"];
                };
            };
        };
    };
    grossesses_calendrier_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meres_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Un terme de recherche. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMereListeList"];
                };
            };
        };
    };
    meres_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MereRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MereRequest"];
                "multipart/form-data": components["schemas"]["MereRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mere"];
                };
            };
        };
    };
    meres_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mere"];
                };
            };
        };
    };
    meres_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MereRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MereRequest"];
                "multipart/form-data": components["schemas"]["MereRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mere"];
                };
            };
        };
    };
    meres_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meres_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMereRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMereRequest"];
                "multipart/form-data": components["schemas"]["PatchedMereRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mere"];
                };
            };
        };
    };
    meres_consentement_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationConsentementRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreationConsentementRequest"];
                "multipart/form-data": components["schemas"]["CreationConsentementRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consentement"];
                };
            };
        };
    };
    meres_revoquer_consentement_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MereRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MereRequest"];
                "multipart/form-data": components["schemas"]["MereRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postes_list: {
        parameters: {
            query?: {
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPosteSanteList"];
                };
            };
        };
    };
    postes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosteSante"];
                };
            };
        };
    };
}
