# Generated by Django 5.2.17 on 2026-09-09 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_postesante_managers"),
        ("beneficiaires", "0001_initial"),
        ("vaccination", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Echeance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("rang", models.PositiveSmallIntegerField(verbose_name="rang de la dose")),
                ("date_ouverture", models.DateField(verbose_name="date d'ouverture")),
                ("date_cible", models.DateField(db_index=True, verbose_name="date cible")),
                (
                    "date_limite",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="date limite"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("due", "Due"),
                            ("en_retard", "En retard"),
                            ("administree", "Administrée"),
                            ("annulee", "Annulée"),
                        ],
                        db_index=True,
                        default="a_venir",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "motif_annulation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contre_indication", "Contre-indication médicale"),
                            ("deces", "Décès"),
                            ("demenagement", "Déménagement"),
                            ("refus", "Refus des parents"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="motif d'annulation",
                    ),
                ),
                (
                    "commentaire_annulation",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                (
                    "enfant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echeances",
                        to="beneficiaires.enfant",
                        verbose_name="enfant",
                    ),
                ),
                (
                    "grossesse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="echeances",
                        to="beneficiaires.grossesse",
                        verbose_name="grossesse",
                    ),
                ),
                (
                    "vaccin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="echeances",
                        to="vaccination.vaccin",
                        verbose_name="vaccin",
                    ),
                ),
            ],
            options={
                "verbose_name": "échéance",
                "verbose_name_plural": "échéances",
                "ordering": ["date_cible", "vaccin__code", "rang"],
            },
        ),
        migrations.CreateModel(
            name="DoseAdministree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_administration",
                    models.DateField(db_index=True, verbose_name="date d'administration"),
                ),
                (
                    "numero_lot",
                    models.CharField(blank=True, max_length=50, verbose_name="numéro de lot"),
                ),
                (
                    "cle_idempotence",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Générée par le client. Empêche les doublons à la synchronisation.",
                        unique=True,
                        verbose_name="clé d'idempotence",
                    ),
                ),
                (
                    "evenement_indesirable",
                    models.TextField(blank=True, verbose_name="événement indésirable"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doses_administrees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="agent",
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doses_administrees",
                        to="accounts.postesante",
                        verbose_name="poste",
                    ),
                ),
                (
                    "remplacee_par",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remplace",
                        to="suivi.doseadministree",
                        verbose_name="remplacée par",
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doses",
                        to="suivi.echeance",
                        verbose_name="échéance",
                    ),
                ),
            ],
            options={
                "verbose_name": "dose administrée",
                "verbose_name_plural": "doses administrées",
                "ordering": ["-date_administration"],
            },
        ),
        migrations.AddIndex(
            model_name="echeance",
            index=models.Index(
                fields=["statut", "date_cible"], name="suivi_echea_statut_d6790e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="echeance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("enfant__isnull", False), ("grossesse__isnull", True)),
                    models.Q(("enfant__isnull", True), ("grossesse__isnull", False)),
                    _connector="OR",
                ),
                name="beneficiaire_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="echeance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enfant__isnull", False)),
                fields=("enfant", "vaccin", "rang"),
                name="echeance_unique_par_enfant",
            ),
        ),
        migrations.AddConstraint(
            model_name="echeance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("grossesse__isnull", False)),
                fields=("grossesse", "vaccin", "rang"),
                name="echeance_unique_par_grossesse",
            ),
        ),
        migrations.AddIndex(
            model_name="doseadministree",
            index=models.Index(
                fields=["poste", "date_administration"], name="suivi_dosea_poste_i_ae82e3_idx"
            ),
        ),
    ]
