# Generated by Django 5.2.17 on 2026-09-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echeance",
            name="statut",
            field=models.CharField(
                choices=[
                    ("a_venir", "À venir"),
                    ("due", "Due"),
                    ("en_retard", "En retard"),
                    ("perimee", "Périmée"),
                    ("administree", "Administrée"),
                    ("annulee", "Annulée"),
                ],
                db_index=True,
                default="a_venir",
                max_length=15,
                verbose_name="statut",
            ),
        ),
    ]
