# Generated by Django 5.2.17 on 2026-09-23 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaires", "0004_mere_compte"),
        ("suivi", "0002_alter_echeance_statut"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rappel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("avant", "Avant l'échéance"),
                            ("jour", "Le jour même"),
                            ("relance", "Relance après retard"),
                            ("confirmation", "Confirmation d'administration"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("application", "Application"),
                            ("simulation", "Simulation"),
                        ],
                        max_length=20,
                        verbose_name="canal",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente d'envoi"),
                            ("envoye", "Envoyé"),
                            ("remis", "Remis au destinataire"),
                            ("lu", "Lu"),
                            ("echec", "Échec"),
                            ("abandonne", "Abandonné"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "langue",
                    models.CharField(default="wo", max_length=5, verbose_name="langue"),
                ),
                (
                    "texte",
                    models.TextField(
                        help_text="Conservé pour tracer ce qui a réellement été envoyé.",
                        verbose_name="texte du message",
                    ),
                ),
                (
                    "planifie_pour",
                    models.DateField(db_index=True, verbose_name="planifié pour"),
                ),
                (
                    "envoye_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoyé le"),
                ),
                (
                    "remis_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="remis le"),
                ),
                (
                    "identifiant_externe",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Permet de relier un accusé de réception à ce rappel.",
                        max_length=255,
                        verbose_name="identifiant chez l'opérateur",
                    ),
                ),
                ("erreur", models.TextField(blank=True, verbose_name="erreur")),
                (
                    "tentatives",
                    models.PositiveSmallIntegerField(default=0, verbose_name="tentatives"),
                ),
                (
                    "echeances",
                    models.ManyToManyField(
                        related_name="rappels",
                        to="suivi.echeance",
                        verbose_name="échéances concernées",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels",
                        to="beneficiaires.mere",
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "rappel",
                "verbose_name_plural": "rappels",
                "ordering": ["-planifie_pour", "-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["mere", "planifie_pour"],
                        name="rappels_rap_mere_id_aa5bc3_idx",
                    ),
                    models.Index(
                        fields=["statut", "planifie_pour"],
                        name="rappels_rap_statut_5ac69f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mere", "type", "planifie_pour"),
                        name="un_seul_rappel_par_type_et_par_jour",
                    )
                ],
            },
        ),
    ]
