# Generated by Django 5.2.17 on 2026-09-09 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaccin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "supprime_le",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "libelle_fr",
                    models.CharField(max_length=100, verbose_name="libellé français"),
                ),
                (
                    "libelle_wo",
                    models.CharField(blank=True, max_length=100, verbose_name="libellé wolof"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "voie",
                    models.CharField(
                        choices=[
                            ("orale", "Orale"),
                            ("intradermique", "Intradermique"),
                            ("intramusculaire", "Intramusculaire"),
                            ("sous_cutanee", "Sous-cutanée"),
                        ],
                        default="intramusculaire",
                        max_length=20,
                        verbose_name="voie d'administration",
                    ),
                ),
                (
                    "doses_par_flacon",
                    models.PositiveSmallIntegerField(default=1, verbose_name="doses par flacon"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "vaccin",
                "verbose_name_plural": "vaccins",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RegleVaccinale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "supprime_le",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cible",
                    models.CharField(
                        choices=[("enfant", "Enfant"), ("mere", "Mère")],
                        default="enfant",
                        max_length=10,
                        verbose_name="cible",
                    ),
                ),
                (
                    "rang",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="rang de la dose",
                    ),
                ),
                (
                    "age_min_jours",
                    models.PositiveIntegerField(verbose_name="âge minimal (jours)"),
                ),
                (
                    "age_cible_jours",
                    models.PositiveIntegerField(verbose_name="âge cible (jours)"),
                ),
                (
                    "age_limite_jours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Fin de la fenêtre de rattrapage. Vide si sans limite.",
                        null=True,
                        verbose_name="âge limite (jours)",
                    ),
                ),
                (
                    "intervalle_min_jours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Délai minimal depuis la dose précédente. Vide pour la première dose.",
                        null=True,
                        verbose_name="intervalle minimal (jours)",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "vaccin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regles",
                        to="vaccination.vaccin",
                        verbose_name="vaccin",
                    ),
                ),
            ],
            options={
                "verbose_name": "règle vaccinale",
                "verbose_name_plural": "schéma vaccinal",
                "ordering": ["cible", "age_cible_jours", "vaccin__code", "rang"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("supprime_le__isnull", True)),
                        fields=("vaccin", "cible", "rang"),
                        name="regle_unique_par_vaccin_cible_rang",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("age_min_jours__lte", models.F("age_cible_jours"))),
                        name="age_min_avant_age_cible",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("age_limite_jours__isnull", True),
                            ("age_limite_jours__gte", models.F("age_cible_jours")),
                            _connector="OR",
                        ),
                        name="age_limite_apres_age_cible",
                    ),
                ],
            },
        ),
    ]
