# Generated by Django 5.2.17 on 2026-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccin",
            name="protege_contre",
            field=models.CharField(
                blank=True,
                help_text="Formulation courte, destinée aux bénéficiaires.",
                max_length=120,
                verbose_name="protège contre",
            ),
        ),
    ]
