# Generated by Django 5.2.17 on 2026-09-09 00:14

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="utilisateur",
            managers=[
                ("objects", apps.accounts.models.GestionnaireUtilisateur()),
            ],
        ),
    ]
