# Generated by Django 5.2.17 on 2026-09-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_utilisateur_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="postesante",
            managers=[],
        ),
    ]
