# Generated by Django 5.2.17 on 2026-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_postesante_managers"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="utilisateur",
            name="agent_et_superviseur_ont_un_poste",
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("agent", "Agent de santé"),
                    ("superviseur", "Superviseur de district"),
                    ("admin", "Administrateur"),
                    ("beneficiaire", "Bénéficiaire"),
                ],
                default="agent",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
        migrations.AddConstraint(
            model_name="utilisateur",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["admin", "beneficiaire"]),
                    ("poste__isnull", False),
                    _connector="OR",
                ),
                name="agent_et_superviseur_ont_un_poste",
            ),
        ),
    ]
