# Generated by Django 5.2.17 on 2026-09-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_utilisateur_agent_et_superviseur_ont_un_poste_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="doit_changer_mot_de_passe",
            field=models.BooleanField(
                default=False,
                help_text="Vrai après une création ou une réinitialisation par un tiers : un mot de passe transmis par autrui n'est pas un secret.",
                verbose_name="doit changer son mot de passe",
            ),
        ),
    ]
