# Generated by Django 5.2.17 on 2026-09-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_utilisateur_doit_changer_mot_de_passe"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "acte",
                    models.CharField(
                        choices=[
                            ("creation", "Création d'un compte"),
                            ("desactivation", "Désactivation d'un compte"),
                            ("reactivation", "Réactivation d'un compte"),
                            ("reinitialisation", "Réinitialisation du mot de passe"),
                            ("transfert", "Transfert vers un autre poste"),
                            ("changement_role", "Changement de rôle"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="acte",
                    ),
                ),
                (
                    "auteur_identifiant",
                    models.CharField(blank=True, max_length=150, verbose_name="auteur"),
                ),
                (
                    "cible_identifiant",
                    models.CharField(blank=True, max_length=150, verbose_name="cible"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="détail")),
                (
                    "horodatage",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="horodatage"
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actes_administration",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "cible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actes_subis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "acte d'administration",
                "verbose_name_plural": "journal d'audit",
                "ordering": ["-horodatage"],
            },
        ),
    ]
