# Generated by Django 5.2.17 on 2026-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_journalaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="postesante",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Numéro du poste, communiqué aux bénéficiaires.",
                max_length=20,
                verbose_name="téléphone",
            ),
        ),
    ]
