# Generated by Django 5.2.17 on 2026-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_postesante_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalaudit",
            name="acte",
            field=models.CharField(
                choices=[
                    ("creation", "Création d'un compte"),
                    ("desactivation", "Désactivation d'un compte"),
                    ("reactivation", "Réactivation d'un compte"),
                    ("reinitialisation", "Réinitialisation du mot de passe"),
                    ("transfert", "Transfert vers un autre poste"),
                    ("changement_role", "Changement de rôle"),
                    ("creation_poste", "Création d'un poste"),
                    ("modification_poste", "Modification d'un poste"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="acte",
            ),
        ),
    ]
