# Generated by Django 5.2.17 on 2026-09-09 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_postesante_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "date_naissance",
                    models.DateField(blank=True, null=True, verbose_name="date de naissance"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro invalide. Format attendu : +221771234567.",
                                regex="^\\+?[0-9]{7,15}$",
                            )
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[("fr", "Français"), ("wo", "Wolof")],
                        default="wo",
                        max_length=2,
                        verbose_name="langue préférée",
                    ),
                ),
                (
                    "village",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="village ou quartier"
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meres",
                        to="accounts.postesante",
                        verbose_name="poste de rattachement",
                    ),
                ),
            ],
            options={
                "verbose_name": "mère",
                "verbose_name_plural": "mères",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Grossesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "rang",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="rang de la grossesse"
                    ),
                ),
                (
                    "date_reference",
                    models.DateField(verbose_name="date du premier contact prénatal"),
                ),
                (
                    "terme_estime",
                    models.DateField(blank=True, null=True, verbose_name="terme estimé"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("interrompue", "Interrompue"),
                        ],
                        default="en_cours",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grossesses",
                        to="beneficiaires.mere",
                        verbose_name="mère",
                    ),
                ),
            ],
            options={
                "verbose_name": "grossesse",
                "verbose_name_plural": "grossesses",
                "ordering": ["-date_reference"],
            },
        ),
        migrations.CreateModel(
            name="Enfant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("supprime_le", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "identifiant_public",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                ("nom", models.CharField(blank=True, max_length=100, verbose_name="nom")),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")],
                        max_length=1,
                        verbose_name="sexe",
                    ),
                ),
                (
                    "semaines_gestation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Moins de 37 semaines : prématuré.",
                        null=True,
                        verbose_name="semaines de gestation à la naissance",
                    ),
                ),
                (
                    "poids_naissance_grammes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="poids de naissance (g)"
                    ),
                ),
                (
                    "poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enfants",
                        to="accounts.postesante",
                        verbose_name="poste de rattachement",
                    ),
                ),
                (
                    "grossesse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants",
                        to="beneficiaires.grossesse",
                        verbose_name="grossesse",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enfants",
                        to="beneficiaires.mere",
                        verbose_name="mère",
                    ),
                ),
            ],
            options={
                "verbose_name": "enfant",
                "verbose_name_plural": "enfants",
                "ordering": ["-date_naissance"],
            },
        ),
        migrations.CreateModel(
            name="Consentement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("application", "Application uniquement"),
                        ],
                        default="whatsapp",
                        max_length=20,
                        verbose_name="canal accepté",
                    ),
                ),
                (
                    "accorde_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="accordé le"
                    ),
                ),
                (
                    "revoque_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="révoqué le"),
                ),
                (
                    "recueilli_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consentements_recueillis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recueilli par",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consentements",
                        to="beneficiaires.mere",
                        verbose_name="mère",
                    ),
                ),
            ],
            options={
                "verbose_name": "consentement",
                "verbose_name_plural": "consentements",
                "ordering": ["-accorde_le"],
            },
        ),
        migrations.AddIndex(
            model_name="mere",
            index=models.Index(fields=["poste", "nom"], name="beneficiair_poste_i_84f57a_idx"),
        ),
        migrations.AddIndex(
            model_name="mere",
            index=models.Index(fields=["telephone"], name="beneficiair_telepho_95ff3a_idx"),
        ),
        migrations.AddIndex(
            model_name="enfant",
            index=models.Index(
                fields=["poste", "date_naissance"], name="beneficiair_poste_i_43b837_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enfant",
            index=models.Index(fields=["mere"], name="beneficiair_mere_id_be3b3f_idx"),
        ),
    ]
