# Generated by Django 5.2.17 on 2026-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaires", "0002_alter_mere_prenom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enfant",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, verbose_name="prénom"),
        ),
        migrations.AlterField(
            model_name="mere",
            name="prenom",
            field=models.CharField(max_length=100, verbose_name="prénom"),
        ),
    ]
