# Generated by Django 5.2.17 on 2026-09-20 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaires", "0003_alter_enfant_prenom_alter_mere_prenom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mere",
            name="compte",
            field=models.OneToOneField(
                blank=True,
                help_text="Permet à la mère de consulter le carnet de ses enfants.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mere",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compte d'accès",
            ),
        ),
    ]
